unclassified:
  slackNotifier:
    teamDomain: "eclipsefoundation"
    tokenCredentialId: "03a52394-e33f-46fc-be2a-222bf8e9a58f"

  prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectCodeCoverage: false
    collectDiskUsage: true
    collectNodeStatus: true
    collectingMetricsPeriodInSeconds: 120
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: ""
    disabledMetricConfig:
      entries:
      - regexDisabledMetric:
          regex: "jenkins_builds_last_stage_duration.*"
      - regexDisabledMetric:
          regex: "jvm_.*"
      - regexDisabledMetric:
          regex: "vm_memory.*"
      - regexDisabledMetric:
          regex: "jenkins_builds_discard_active.*"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false